"""empty message

Revision ID: 3cf7a34842b4
Revises: 
Create Date: 2019-03-08 01:51:58.239997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf7a34842b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
                    sa.Column('name', sa.VARCHAR(length=49), autoincrement=False, nullable=True),
                    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='banks_id_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('branches',
                    sa.Column('ifsc', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
                    sa.Column('bank_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('branch', sa.VARCHAR(length=74), autoincrement=False, nullable=True),
                    sa.Column('address', sa.VARCHAR(length=195), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('district', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name='branches_banks_fkey'),
                    sa.PrimaryKeyConstraint('ifsc', name='branches_ifsc_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branches')
    op.drop_table('banks')
    # ### end Alembic commands ###
