"""empty message

Revision ID: 808eb8c24ca0
Revises: 3cf7a34842b4
Create Date: 2019-03-08 14:22:08.340711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808eb8c24ca0'
down_revision = '3cf7a34842b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('id', sa.BIGINT(), nullable=False, autoincrement=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
